### ISSUE TITLE
osx install fails silent > changed installer proposal inside :)

### ISSUE THREAD

**Issue by 2075** [Artificial-Engineering/lycheeJS#126]
osx install fails silent with this description
why? because the zip will be loaded into /opt, not lycheejs folder which has 777.

~~therefore either sudo in your script, load the zip into the lychee folder, or add user to wheel like so: ~~
~~`sudo dseditgroup -o edit -a yourfancyusername -t user wheel`~~

**Comment by 2075** [comment]
I propose like this, guessing the following desired dir structure:
```/opt
/opt/lycheejs
sources: /opt/lycheejs/lycheejs
runtime: /opt/lycheejs/bin
```
correct?

I have enabled the progress bar again, as a silent download of the runtime can take longer and user doenst know if it apes or just takes longer ;)
```
#!/usr/bin/env bash

INSTALLER_ROOT=$(cd "$(dirname "$0")"; pwd);
LYCHEEJS_ROOT="$INSTALLER_ROOT/lycheejs";
LYCHEEJS_BR="master";

echo "";
echo "lycheeJS NetInstall 2015-Q4";
echo "";
echo "This installer will download and install lycheeJS to $LYCHEEJS_ROOT";
echo "";

echo "Installing lycheejs...";

echo "Creating temp dir.";
        cd "$LYCHEEJS_ROOT";

echo "Downloading source.";
        curl -LOk --progress-bar https://github.com/Artificial-Engineering/lycheeJS/archive/$LYCHEEJS_BR.zip;

echo "Extracting archive.";
        unzip -q $LYCHEEJS_BR.zip ;
        mv lycheeJS-$LYCHEEJS_BR ./lycheeJS;
        rm master.zip;

echo "Done.";

echo "";
echo "Installing runtimes...";

        curl -LOk --progress-bar https://github.com/Artificial-Engineering/lycheeJS-runtime/archive/master.zip;
        unzip -q master.zip;
        mkdir ./bin
        mv lycheeJS-runtime-master ./bin/runtime;
        rm master.zip;

echo "Done.";

echo "";
echo "Configuring lycheeJS ...";

#       cd $LYCHEEJS_ROOT;
        ./bin/configure.sh;

echo "Done.";

echo "";
echo "In order to boot lycheeJS, you need to start Sorbet.";

        echo "";
        echo "You can modify all profiles located at $LYCHEEJS_ROOT/bin/sorbet/";
        echo "Start Sorbet by executing this command:";
        echo "";
        echo "cd $LYCHEEJS_ROOT; ./bin/sorbet.sh start development;";
        echo "";
```

At least on OSX this seemed to work out now.

Cheers.

**Comment by cookiengineer** [comment]
Thanks for the hint!

I fixed it in the [lycheeJS-bundle repo](https://github.com/Artificial-Engineering/lycheeJS-bundle/commit/ff8a708bdf9050b200a5d7d1cf7183e86345531e) so the fixes are merged in with the upcoming `2016-Q1` release.

If you want to make sure that everything is up to date, you can change the branch from `master` to `development`. The upcoming release is currently scheduled for 27th February, so until then all the features from the last months stay on the `development` branch.


Currently, we need `root` rights for at least the `./bin/configure.sh` call because the `lycheejs-helper` binary needs to be a URL handler that is available in `/usr/bin` and not in `/usr/bin/local`. That is why there's a `sudo ./bin/configure.sh`.

If you don't want the native integrations, you can still use `./bin/configure.sh --no-integration`, but that will disintegrate the `Editor` and `Ranger` from its interaction capabilities with the rest of the stack.

**Comment by 2075** [comment]
at least the packages install now into the expected folders, i guess the sudo isnt such a big problem. after fixing the script no errors occured at all :) big up!
