### ISSUE TITLE
cultivator api browser top right buttons cut off

### ISSUE THREAD

**Issue by 2075** [Artificial-Engineering/lycheeJS#127]
<img width="721" alt="screen shot 2016-02-17 at 21 56 57" src="https://cloud.githubusercontent.com/assets/1140449/13124623/9898d872-d5c1-11e5-9980-bc7909b8b056.png">

**Comment by cookiengineer** [comment]
Can you verify that the fix is working on your Firefox?

The previous CSS was working in Chrome and other Blink-based Browsers, so this is kind of a legacy issue with Firefox. We currently only support Chrome and other Blink Browsers officially, because Firefox has no [Error.captureStackTrace](https://github.com/Artificial-Engineering/lycheeJS/blob/development/libraries/lychee/source/core/Debugger.js#L162) API which is essentially necessary in the developer workflow.
