### ISSUE TITLE
Fertilizer > html-webview aapt Failure

### ISSUE THREAD

**Issue by CodeKittey** [Artificial-Engineering/lycheejs#140]
rror: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/opt/lycheejs-edge/bin/runtime/html-webview/android-toolchain/sdk-linux/x86_64/build-tools/21.1.2/aapt''
:app:mergeDebugResources FAILED

BUILD FAILED

Total time: 36.95 secs
FAILURE (Android build)  
  cp: cannot stat ‘/opt/lycheejs-edge/projects/cultivator/ranger/build/html-webview/main/index.js’: No such file or directory

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/opt/lycheejs-edge/bin/runtime/html-webview/android-toolchain/sdk-linux/x86_64/build-tools/21.1.2/aapt''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
cp: cannot stat ‘/opt/lycheejs-edge/projects/cultivator/ranger/build/html-webview/main/index.js’: No such file or directory
cp: cannot stat ‘/opt/lycheejs-edge/projects/cultivator/ranger/build/html-webview/main/index.js’: No such file or directory  
    
  fertilizer: FAILURE ("/projects/cultivator/ranger | html-webview/main") at "package" event

**Comment by cookiengineer** [comment]
Consulting stackoverflow, a library for aapt seems to be missing. Going to debug this some more when I have more time.

**Comment by cookiengineer** [comment]
It seems as the aapt binary is not executable on every system. To fix this, we need to integrate the chmod +x calls into the [bin/configure.sh]() script in order to prevent this from happening.

The [aapt binary](https://github.com/Artificial-Engineering/lycheejs-runtime/blob/master/html-webview/android-toolchain/sdk-linux/x86_64/build-tools/21.1.2/aapt) itself exists as expected and the repository has it cached with executable rights.
