### ISSUE TITLE
Installation was ok but still can' run editor etc

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [Artificial-Engineering/lycheejs#154]
Hi @cookieengenier
now i setup a virtual box on mac osx an setup Ubuntu 16.04 on it. Installation was fine but i still can't access the editor. see screenshot.
![virtualbox_lycheejs_14_07_2016_04_06_33](https://cloud.githubusercontent.com/assets/9912964/16825973/b5c4ef2c-4979-11e6-88c1-2e44fff677ae.png)
And now ?

**Comment by AlexUnderMicrocontRoll** [comment]
try something other things. just one error with node-sdl
fertilizer: FAILURE ("/libraries/lychee | node-sdl/dist") at "init" event 
I have downloaded node-sdl-runtime. run configure.sh script. --> works.
But when i try to run the package.sh from node-sdl-runtime i get 
the following error:
Sorry, your computer is not supported. (linux / x86_64)

**Comment by cookiengineer** [comment]
If you don't want to use the Web variants you can also use the native tools if you installed lycheejs via a bundle or the net installer:

- Run `lycheejs-editor` from the Applications (the GUI Menu like the Ubuntu Icon top left). It's integrated there already, the `lycheejs-ranger` too. You can also search simply for `lycheejs`.
- If no lycheejs-editor there, you forgot to run `sudo ./bin/maintenance/do-install.sh`.


**Solution 1 (Ubuntu VM)**:
- `sudo apt-get install chromium` and use Chromium as a Browser.

**Solution 2 (Native OSX)**:
- Install [brew](http://brew.sh/) as a package manager (if not already installed).
- Run the net installer again (see below, if it is already installed it will be replaced with a working installation that is up-to-date). The sudo is important, because some tasks need root rights.
- Use Chrome as a Browser or start `lycheejs-editor` from the Terminal.

```bash
sudo bash -c "$(curl -fsSL https://lychee.js.org/install.sh)";
```

**Other**:

The warning for node-sdl is okay, as the fertilizer adapter is not ready (yet).

lychee.js is known to work on my OSX system (El Capitan), but it requires explicitely brew to be installed beforehand - because macports might fail having too old packages.

Oh gosh, that's an old Firefox running there with no support for Web Components or Custom Elements :-/ The welcome page uses Web Components, but everything else in lychee.js is using a DOM free setup by default. I have Firefox 47.0 on my Ubuntu machine, that is working and has support for Web Components. However, please use Chrome/Chromium/Opera as you are going to need Debugger support sooner or later.

**Comment by AlexUnderMicrocontRoll** [comment]
@cookiengineer it works with chromium.
