### ISSUE TITLE
Installation on Windows is not clear and the Documentation is from another Dimension

### ISSUE THREAD

**Issue by 10Dev** [Artificial-Engineering/lycheejs#175]
1. The Readme refers to a Windows .exe file but I can't find that in the Releases or Runtime Releases

2. It seems likely that if I take advantage of the Ubuntu Bash Shell on Windows 10 your install procedure will not work since you seem to have a lot of Linux/Unix assumptions which seems contradictory to potential widespread uptake of your concept. Npm, Gulp, Yeoman, Yarn all run well on Windows, but Bash is a large but not complete subset of Linux. 

3. Also, if the Windows issue is ignored, you have a Javascript based system that essentially becomes far less portable and flexible by taking on non-JS dependencies when JS tools will do the job.

4. Your documentation is close to incomprehensible. All I can figure out without being able to install anything is that you seem to have a clever idea around P2P AI assisted app development without any simple "in your face" examples to light up comprehension.

5. Although similar to my first point, the lack of a clear and easy route to Windows means that over 90% of everyone that looks at your idea will forget about it 5 minutes later when they can't test it out. That means an order of magnitude less uptake, less bug reports, less code contrib.

6. One idea that might assist with the comprehension idea is an online test  JS REPL/IDE like the Babylon.js Playground or WhitestormJS or Goo or Playcanvas etc so people can try it out when they visit your web page. A side effect sort of marketing advantage for JS based software...

**Comment by cookiengineer** [comment]
1. and 2. We currently have no support for Windows as a developer host platform, only OSX, BSDs and Unices. That is due to issues with lack of proper gcc, binutils and coreutils and we cannot afford to go to Windows here. The quality of options is too varying, so we recommend to use Windows Subsystem for Linux (Ubuntu Bash) which might work if you modify the [./bin/maintenance/do-install.sh](https://github.com/Artificial-Engineering/lycheejs/blob/development/bin/maintenance/do-install.sh#L97), which installs the dependencies on the host machine.

3. The lycheejs Engine is not a library, it is a full-blown cross-compiler toolchain + app analytics + machine intelligence engine. You can see it as "Unity for Apps" or "Unity for Automation" or something like that. There's always the possibility to use lycheejs as a library only, using the [lychee.js Library via NPM or Bower](https://github.com/Artificial-Engineering/lycheejs-library). But note that pretty much all AI automation features are gone then and you can only use all components and definitions of the lychee library itself. If you need help on how to use it, take a look at [unimatrix-zero](https://github.com/cookiengineer/unimatrix-zero) as an example project that makes use of the `lychee.assimilate('path/to/Definition.js')` method to include your own definition files.

4. Thanks for your feedback. Currently the ES/HyperNEAT update and the lack of tutorials is not the best one; yet not possible to be delivered over the last weeks due to personal work. Need to get money to buy food and wasn't able to go fulltime lycheejs anymore since money burnt down around September.

5. Again, sorry for inconvenience: No Windows as developer host support, we currently can only cross-compile to Windows as a target platform. There's just too many problems on non-Unices when it comes to the automation pipeline for the [lycheejs-runtimes](https://github.com/Artificial-Engineering/lycheejs-runtime) and their build toolchains. Let alone java and binutils problems for Android SDK, Blackberry and FirefoxOS; which are close to impossible to automate in a non-manual manner.

6. Thank you very much for taking the time and to write up the feedback. I realize that most of the stuff is not "production-ready" and more in kind of an R&D state at the moment. I realize that the lycheejs-guide is totally incomplete and I realize that your experience coming from Windows is not the best one.

------

Please try to understand that delivering OSX, BSDs and Unices is far more easy than Windows (given I have no effing clue if you use cygwin, msys, or any other non-complete bash environment). Quality of binutils and coreutils on Windows is of very varying support, so it's not guaranteed to work with a failsafe shell script installer. As the development overhead for delivering Windows is at least double the filesize (due to Powershell or WSL) and at least double the work time (due to mentioned problems) support as a development host was dropped in 2016-Q1.

For now I can only recommend trying out either using a GNU/Unix-alike VM or the [Dockerfile](https://github.com/Artificial-Engineering/lycheejs-bundle/blob/master/bin/package/docker/Dockerfile).

There are currently no other ways to go to Windows without compromising pretty much 90% of our automation features that are necessary for the AI knowledge communication.

**Comment by 10Dev** [comment]
Thanks for your detailed response.

I can't be disappointed (yet) about the Windows situation because like chicken and egg without being able to run your system, I don't know what I am missing.

So from your point of view, 9 out of 10 people that see your website will have to keep going because the vast majority of the world uses Windows and you are missing the opportunity to get bug testers, feedback and maybe dev help but since you did have a Windows dev setup previously maybe you didn't get sufficient interest to justify the extra design effort.

I can't understand enough of what your project actually does or how it works or even what it is supposed to achieve other than the words you use in your descriptions seem to imply a novel and interesting architecture. If you are JavaScript based, you should be able to convert all your tool chains to JavaScript/Node but it isn't even clear what exactly you are building on-the-fly - if it is Mobile, then Xamarin would give you IOS, Android and Windows Mobile and runs on Windows and OSX and whatever the mobile component of your system might be doing, IOS would be far more useful than Blackberry or FirefoxOS  

But I'm just kind of brainstorming out loud here since you made such an effort to respond and maybe none of these thoughts are very applicable.

I would suggest making lots of diagrams as the fastest way of communicating your ideas on the website since the words are just not creating any mental model and I'm usually pretty good of making sense of most designs of things so diagrams could help many visitors to your project I think.

**Comment by cookiengineer** [comment]
> but since you did have a Windows dev setup previously maybe you didn't get sufficient interest to justify the extra design effort.

Currently the exact world-wide amount of our potential Windows users of the framework is 1 (that's you).

The rest uses Linux, BSDs or OSX. And if they use Windows, they simply use Docker as everybody else does anyways. Going from bash to cmd.exe is impossible as stated. I'm not a guy that tries to build tools for an operating system. I want to get shit done. And that's impossible on Windows. If you still can't understand that, I honestly don't care. Move on with your life and do whatever you did before. I'm not here to tell you what you miss.

> (...) because the vast majority of the world uses Windows

Have you seen the internet?

Basically what you're trying to tell me is that I should use Windows because everybody uses Windows. It feels like telling Linus Torvalds that Linux is useless, because there's a proprietary alternative existing. If you tell me to use Xamarin and tell me that you can compile to iOS via XCode on Windows, you ain't know shit what Xamarin can do. And yes, compiling from Windows to iOS ain't possible, so your argument of using Xamarin here (from your point of having read only our README) is totally invalid because Xamarin in fact cannot cross compile from Windows to iOS as the [darling](https://github.com/darlinghq/darling) project as the only even remotely theoretically possible solution is so damn not ready for production.

If you want to compile to iOS, you need to install XCode, and you need to buy a Macbook. That's how it works. As just as every single other framework on the planet needs to; lychee is a superset of Xamarin and can do more, because Xamarin cannot compile standalone operating system images, neither can it support ATMel and embedded architectures (via jerryscript) and neither can it put out real standalone exe-files of applications without manual labour.


I don't think that this discussion will lead to a meaningful discussion or a helpful article to other users. So it's closed for the sake of peace.
