### ISSUE TITLE
Installer needs fixing for WSL (Windows 10)

### ISSUE THREAD

**Issue by cocoapuffs** [Artificial-Engineering/lycheejs#193]
The `install.sh` file needs some fixes for being usable with the Windows Subsystem for Linux (WSL) and its Ubuntu environment.

The Ubuntu environment is stripped down to its essentials, so the installer has to check _before_ whether these things are available or not.

- [x] line `112`: unzip not found - Requires a `sudo apt-get install unzip` before.

- [x] `./bin/maintenance/do-install.sh` needs `sudo apt-get update` to be placed beforehand, otherwise `icnsutils` package is not available in local package index.

- [x] Integration of `sudo apt-get install npm` and `sudo npm install -g eslint`.

## System / Libraries / Projects

Please replace these in order to let us know what
is broken. If you don't know what to enter in each
line, just replace the answer with an `-`.

- **Operating Systems**: `Windows`
- **Platforms**: `all`

**Comment by cocoapuffs** [comment]
After above tasks are resolved in an automated manner, lychee.js runs perfectly fine on WSL with Ubuntu on Windows 10:

![https://i.imgur.com/m0XjWut.png](https://i.imgur.com/m0XjWut.png)

**Comment by cookiengineer** [comment]
Additionally, we might need an A-Z test that is hosted on travis / circle which constantly does the reinstallation from scratch for all operating systems. I'm not sure whether this will exceed the memory limitations, because it will need around 4-8 GB.

Depending on whether it is feasible or not, a github CI integration here might be the way to go to resolve future minor bugs/glitches like this.

**Comment by cookiengineer** [comment]
Turns out that the `eslint` integration is harder to ship than the other parts. Regarding `eslint`, we probably have to maintain or create a standalone fork that removes all unnecessary dependencies and the babel toolchain; so that we can easily integrate it into the `./bin/eslint` folder and/or create binaries with the `lycheejs-runtime` repository builds.

I'm gonna investigate this the next couple days in order to figure out which is the preferable and easier to maintain-in-future solution.

**Comment by cookiengineer** [comment]
All things have been integrated, except the `eslint` part which will be tracked from now on in the Termux Support issue #195
