### ISSUE TITLE
Fertilizer > node-sdl

### ISSUE THREAD

**Issue by pyros2097** [Artificial-Engineering/lycheejs#66]
Is the iojs sdl version already done or is it WIP? I tried to port [node-sdl](https://github.com/creationix/node-sdl) to iojs using NAN 2 but ran into some issues as iojs 3 is very unstable now. I have started using node-ffi to directly make bindings to sdl and it seems to work but i don't know how much of a performance issue it might have? So is there an open project where i can check it out or maybe contribute?
And what about iOS support iojs v8 isn't allowed on it. There is the alternative jxcore
And if this is implemented wont people use this as the default renderer for native desktops and apps as it will be more performant the html?

**Comment by martensms** [comment]
The iojs-sdl runtime is currently WIP. Last year we had support for v8gl, our old runtime.

Currently I simply had no time to dig into compiling and fixing the stuff in https://github.com/LazerUnicorns/node-sdl-runtime into standalone binaries yet.

I had the same issues with iojs, it's heavily unstable porting the old bindings, because the API of v8 heavily changed since Turbo refactor and node-gyp seems to be totally broken at least on my Ubuntu 15.04 machine.

Regarding iOS: Still the state within lycheeJS here is that we have no ready binaries that we can integrate with the runtime repository. BUT I found [this SDL bindings project](https://github.com/flyover/node-sdl2) by accident. I haven't tried it out, but it seems as it has [valid xcode project files](https://github.com/flyover/node-sdl2/blob/master/node-sdl2-ios/node-sdl2.xcodeproj/project.pbxproj#L154).

I have no OSX machine atm, but that might be worth trying out. Dunno what the nan library in there is though.

**Comment by cookiengineer** [comment]
Just wanted to give a quick update here.

The last couple days I had time to work on the new [node-sdl-runtime](https://github.com/Artificial-Engineering/node-sdl-runtime), which is going to be the implementation we are using in lycheeJS. It works at least on Linux amd64 (Ubuntu, Arch and Fedora tested).

I already uploaded some dylibs I found on the web, but can't verify them because of lacking OSX hardware.

If OSX and Linux support both work fine, we can switch to the runtime and have bindings in place for lycheeJS as a fertilizer template and an extra platform tag.

The bindings and adapters won't make it into 2016-Q1 (which is going to be released within the next 2 days). However, we planned to have these bindings (if the runtime is working on OSX and Linux at least) in the Q2 release.

**Comment by pyros2097** [comment]
Great work. I see that you created SDL bindings using FFI instead of doing the native bindings which is whole lot easier and cleaner to understand. I will be looking into this in the future to see how well it goes and how your going to make it work on different platforms and maybe get some wisdom from them.
But I have since jumped to golang and started creating a Next-Gen Isomorphic Application Engine for Embedded, Console, Mobile, Server and Desktop using it (Still have no clue how I'm going to be doing it for the web side atleast). It makes me a lot more productive but I still miss nodejs and its single event loop (which makes it amazingly suitable for games).

**Comment by cookiengineer** [comment]
Yep, I had to write a small prototype first to evaluate it. FFI is pretty damn awesome regarding the fact that you can statically link / compile the final bindings. Much cleaner to understand and has no dirty hacks with the node.js source code itself. The only nagging part is, of course, the removal of all unnecessary source code in all node_modules.

Neat, is your [spike](https://github.com/pyros2097/spike) the engine you were mentioning? Gotta take a glimpse on it and try it out in the next days.

In lycheejs the hardest part was the event system and the environment serialization part, which both led to like 4 or 5 refactors each.

I also want to try out Rust for the purpose of building a small runtime. The compiler chain behind Rust seems to be pretty damn good when it comes to static code analysis and automated parallelism of execution branches.

**Comment by pyros2097** [comment]
Oh you can statically link them I din't know that.
My [spike](https://github.com/pyros2097/spike) game engine is abandoned after golang people stopped working on their mobile framework. It was meant to work only on mobiles and linux and i was munually handling the X11 window create and X11 events and it was very hard to implement it so I stopped working on it.

So now I wanted to try again and decided to create an isomorphic framework like yours and inspired by react and use SDL since it is cross platform and handles everyting for you. The only drawback of SDL is that it isn't implemented for the web you have have to manually use webGL and manually handle the events or write a shim and using [goxjs](https://github.com/goxjs/gl) and [gopherjs](http://gopherjs.org/) compile my programs for the web also.

I have actually tried rust and worked with it. I still feel its a bit unstable and not production ready as of yet and easy to use. The borrow checker in rust is very hard to figure out and takes a lot of time in learning it. But one thing I like about rust is its safely check this framework out https://github.com/tomaka/glium and this one https://github.com/tomaka/glutin. And one thing about rust you don't need C libraries or frameworks at all. Everything even the standard lib is implemented in Rust.

**Comment by pyros2097** [comment]
Ha Ha!. Anyway I found this isomorphic gui framework which actually works on all platforms https://github.com/yglukhov/nimx. Going to learn something from this later.

**Comment by cookiengineer** [comment]
Sorry for not coming back to you in time, we were a bit busy with the 2016-Q1 release and the website / botnet stuff.

Regarding the SDL implementatins: I also tried out glium, but have no clue if that would be overdone. The problems with node-sdl is that native bindings will probably have to be maintained harshly whilst the node-ffi bindings can stay the same without recompilation. Recompilation with node-gyp sucks hard :(

Gonna checkout glutin, haven't heard of it before.

The nimx framework is very neat to read. Their bindings seem to be pretty straight-forward. Gonna look if they have some file dialogs implemented already.

The only problems that might occur with node-sdl so far is that I have no clue on how to get a GTK file selection dialog integrated. Well, and the isomorphic variants for Windows and OSX.

I might wanna use a static compiled variant of a library like [wxWidgets](http://www.wxwidgets.org/) or [XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL), but I'm still unsure 'bout it.

**Comment by cookiengineer** [comment]
Okay, I'm sold to libtk. I think libtk is exactly what I need:

Their [Windows and Dialogs](http://www.tkdocs.com/tutorial/windows.html#wm) is everything I need, as the FS layer can be abstracted totally inside nodejs itself.

There are also some experimental bindings in the [nodetcltk](https://github.com/nacmartin/nodetcltk) repo (very crappy implemented via eval in C context though) that led me to the idea.

**Comment by pyros2097** [comment]
Nim does have one for file dialogs https://github.com/SSPkrolik/nim-native-dialogs it seems fairy simple.
I remember trying ffi for gtk and it was a whole mess. It uses a lot of function pointers and callbacks in I didn't know how to pass them in ffi.
I have created some applications with wxWidgets but since its C++ you might need to use wxc or something which might get more complicated.

**Comment by cookiengineer** [comment]
Jep, might make sense for me to fork a library and make a smaller library out of it without all the bloat as the lycheeJS adapters only need dialogs for file input/output and maybe drag/drop on them (which is supported by the OS-level API anyways).
