### ISSUE TITLE
Editor > Library support (/libraries/tutorial)

### ISSUE THREAD

**Issue by CodeKittey** [Artificial-Engineering/lycheejs#99]
The lycheeJS project needs an live hacking editor with a live update result view on the side.
e.g. for live editing some serialized JSON and see live updates on a timeline.

**Comment by martensms** [comment]
A cool idea would be to found a /lib/tutorial library that can be reused among different set of tutorials. It can be reused as a boilerplate for tutorials - wherein only single definitions need to be modified - so the simulator part is easy to implement and trace what kind of changes the editor made.

That could be pretty awesome if the code view of the live hacking editor highlights just a few lines of code and makes them modifiable. Might make sense to have something like toAPI() as a method on the lychee.Definition interface, so that it can be traced automatically.

**Comment by 2075** [comment]
hmmmm live editor, where is the damn upvote button on github?

**Comment by cookiengineer** [comment]
This stuff is related to the Editor, as the Editor will have Entities (and libraries) that you can reuse for your project.

**Comment by cookiengineer** [comment]
The tutorials are now integrated in the lychee.js Guide, so no dependency to the Editor here. As the Breeder can fork now, it can also be used to incrementally follow the Tutorials.
